refactor: cleanup bin scripts

diff --git a/.dotfiles/bin/git-quickfix b/.dotfiles/bin/git-quickfix
--- a/.dotfiles/bin/git-quickfix
+++ b/.dotfiles/bin/git-quickfix
@@ -16,6 +16,7 @@
 #     git quickfix @{u}..
 #     git quickfix -m modified
 #     git quickfix -m staged
+#     git quickfix abcdef -- path/to/file.foo
 
 NAME=$(basename "$0")
 TEMP="${TMPDIR-/tmp}/${NAME}.${$}.$(awk \
@@ -39,8 +40,8 @@ while getopts hm:x opt; do
             ;;
         x) set -x ;;
         *)
-            echo "Invalid flag"
-            exit
+            echo "Invalid flag: $opt"
+            exit 1
             ;;
     esac
 done
@@ -51,43 +52,27 @@ mkdir -p -m 700 "$TEMP"
 
 {
     if [ "$mode" = 'modified' ]; then
-        git diff -p -U0 --diff-filter=AM
+        git diff -p -U0 --diff-filter=AM "$@"
     elif [ "$mode" = 'staged' ]; then
-        git diff --cached -p -U0 --diff-filter=AM
+        git diff --cached -p -U0 --diff-filter=AM "$@"
     else
         case $1 in
-            *..*) cmd='diff' ;;
-            *) cmd='diff-tree' ;;
+            *..*) git diff -p -U0 --diff-filter=AM -r "${@:-HEAD}" ;;
+            *) git show --first-parent -m -p -U0 --diff-filter=AM "${@:-HEAD}" ;;
         esac
 
-        git "$cmd" -p -U0 --diff-filter=AM -r "${1:-HEAD}"
     fi
-} | awk '/^diff/ {
-          in_hunk=0
-          if (NR != 1 ) { printf("--\n") }
-        }
-
-        /^\+\+\+ / {
-          fname=substr($2, 2)
-        }
-
-        /^@@ / {
-          in_hunk=1
-          nr=substr($3, 2)
-          sub(/,.*/, "", nr)
-          printf(".%s:%s:%s\n", fname, nr, $0)
-          next
-        }
-
-        in_hunk {
-          printf("%s\n", $0)
-        }
-    ' >"$QFLIST"
+} | diff-to-quickfix >"$QFLIST"
 
 if [ ! -s "$QFLIST" ]; then
     printf 'No %s changes.\n' "$mode" 1>&2
     exit 1
 fi
 
-# bd1 deletes the initial "[No Name]" buffer (reqs :set hidden). Better way?
-$EDITOR +bd1 -q "$QFLIST"
+# Open with Vim if outputting to a tty, otherwise just output directly.
+if [ -t 1 ]; then
+    # bd1 deletes the initial "[No Name]" buffer.
+    $EDITOR +bd1 -q "$QFLIST"
+else
+    cat "$QFLIST"
+fi
diff --git a/.dotfiles/bin/httpdir b/.dotfiles/bin/httpdir
--- a/.dotfiles/bin/httpdir
+++ b/.dotfiles/bin/httpdir
@@ -13,6 +13,9 @@ HTTP_METHOD=''
 HTTP_PATH=''
 HTTP_VERSION=''
 
+# shellcheck disable=2254
+fnmatch() { case "$2" in $1) return 0 ;; *) return 1 ;; esac }
+
 rep() {
     local status="${1:?Status is required.}"
     shift 1
@@ -48,8 +51,8 @@ http() {
     fi
 
     local rpath="$PWD$HTTP_PATH"
-    # shellcheck disable=2081
-    if [ "$rpath" = *..* ]; then
+
+    if fnmatch '*..*' "$rpath"; then
         rep 400
         exit
     fi
@@ -137,7 +140,10 @@ main() {
                 ssl=",cert=/tmp/${NAME}.crt,key=/tmp/${NAME}.key,verify=0"
                 listen="OPENSSL-LISTEN"
                 ;;
-            *) echo "Invalid flag" && return ;;
+            *)
+                echo "Invalid flag: $opt"
+                exit 1
+                ;;
         esac
     done
     shift $((OPTIND - 1))
diff --git a/.dotfiles/bin/npm-deps-report b/.dotfiles/bin/npm-deps-report
--- a/.dotfiles/bin/npm-deps-report
+++ b/.dotfiles/bin/npm-deps-report
@@ -1,6 +1,5 @@
 #!/usr/bin/env sh
 
-
 # Output how many sub-dependencies each npm dependencies has
 # https://github.com/whiteinge/dotfiles/blob/master/bin/npm-deps-report
 #
@@ -14,7 +13,10 @@ while getopts h opt; do
             awk 'NR == 1 { next } /^$/ { exit } { print substr($0, 3) }' "$0"
             exit
             ;;
-        *) echo "Invalid argument" && return 1 ;;
+        *)
+            echo "Invalid flag: $opt"
+            exit 1
+            ;;
     esac
 done
 shift $((OPTIND - 1))
diff --git a/.dotfiles/bin/qr-wifi b/.dotfiles/bin/qr-wifi
--- a/.dotfiles/bin/qr-wifi
+++ b/.dotfiles/bin/qr-wifi
@@ -5,28 +5,31 @@
 # https://feeding.cloud.geek.nz/posts/encoding-wifi-access-point-passwords-qr-code/
 
 while getopts ":s:p:" _opt; do
-  case "$_opt" in
-    s) _ssid="$OPTARG" ;;
-    p) _pass="$OPTARG" ;;
-    *) echo "$0 [-s ssid] [-p pass]" ; exit 2 ;;
-  esac
+    case "$_opt" in
+        s) _ssid="$OPTARG" ;;
+        p) _pass="$OPTARG" ;;
+        *)
+            echo "$0 [-s ssid] [-p pass]"
+            exit 2
+            ;;
+    esac
 done
 
 for _dep in feh qrencode; do
-  if ! command -v "$_dep" >/dev/null 2>&1; then
-    echo "$_dep required but not found, ending run."
-    exit 1
-  fi
+    if ! command -v "$_dep" >/dev/null 2>&1; then
+        echo "$_dep required but not found, ending run."
+        exit 1
+    fi
 done
 
 while [ -z "$_ssid" ]; do
-  printf 'SSID: '
-  read -r _ssid
+    printf 'SSID: '
+    read -r _ssid
 done
 stty -echo
 while [ -z "$_pass" ]; do
-  printf 'Password: '
-  read -r _pass
+    printf 'Password: '
+    read -r _pass
 done
 printf '\n'
 stty echo
